var matteo = {
  "login": "matteomanzo",
  "id": 8677696,
  "avatar_url": "https://avatars.githubusercontent.com/u/8677696?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/matteomanzo",
  "html_url": "https://github.com/matteomanzo",
  "followers_url": "https://api.github.com/users/matteomanzo/followers",
  "following_url": "https://api.github.com/users/matteomanzo/following{/other_user}",
  "gists_url": "https://api.github.com/users/matteomanzo/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/matteomanzo/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/matteomanzo/subscriptions",
  "organizations_url": "https://api.github.com/users/matteomanzo/orgs",
  "repos_url": "https://api.github.com/users/matteomanzo/repos",
  "events_url": "https://api.github.com/users/matteomanzo/events{/privacy}",
  "received_events_url": "https://api.github.com/users/matteomanzo/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Matteo Manzo",
  "company": "",
  "blog": "",
  "location": "London, UK",
  "email": "imatteo.manzo@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 39,
  "public_gists": 0,
  "followers": 15,
  "following": 9,
  "created_at": "2014-09-06T11:47:43Z",
  "updated_at": "2015-02-04T16:51:23Z"
};

var bebbs = {
  "login": "bebbs",
  "id": 7558797,
  "avatar_url": "https://avatars.githubusercontent.com/u/7558797?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/bebbs",
  "html_url": "https://github.com/bebbs",
  "followers_url": "https://api.github.com/users/bebbs/followers",
  "following_url": "https://api.github.com/users/bebbs/following{/other_user}",
  "gists_url": "https://api.github.com/users/bebbs/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/bebbs/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/bebbs/subscriptions",
  "organizations_url": "https://api.github.com/users/bebbs/orgs",
  "repos_url": "https://api.github.com/users/bebbs/repos",
  "events_url": "https://api.github.com/users/bebbs/events{/privacy}",
  "received_events_url": "https://api.github.com/users/bebbs/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Josh Bebbington",
  "company": "",
  "blog": "",
  "location": "London, UK",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 36,
  "public_gists": 0,
  "followers": 13,
  "following": 14,
  "created_at": "2014-05-12T14:24:28Z",
  "updated_at": "2015-02-04T18:56:17Z"
};

exports.matteo = matteo;
exports.bebbs = bebbs;
